sudo: required

language: go

services:
  - docker

go:
  - 1.8.x

install:
  - go get github.com/braintree/manners
  - go get github.com/qopher/go-torrentapi
  - go get github.com/boltdb/bolt
  - go get github.com/gorilla/feeds
  
after_success:
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o movierss .
  - docker build -t teambrookie/movierss:$TRAVIS_BRANCH .
  - docker login -u="$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push teambrookie/movierss:$TRAVIS_BRANCH;
